server:
  port: 14001

spring:
  application:
    name: happy-admin-api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.208:13306/sp_test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: slyours@123

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

  redis:
    host: 192.168.0.208
    port: 16379
    database: 2
    password: slyours@123

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  security:
    matchers: "/webjars/**,/favicon.ico,/captcha,/login,/logout,/test,/doc.html**,/swagger-resources,/v2/api-docs**"

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0

happy:
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长，7天，单位秒
    expire: 604800
    header: Authorization

logs:
  path: /Users/songyangpeng/workspace/java/lucky-admin/logs